/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // We define it explicitly here to ensure logical grouping and ordering.
  // This is the main sidebar for the entire documentation.
  documentationSidebar: [
    // The first item is the landing page of the documentation.
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'separator',
    },
    // Category for Core Calculator features.
    // We use 'autogenerated' to automatically create a sidebar category
    // from all the .md/.mdx files within the 'core-calculator' directory.
    // This is a maintainable approach as it doesn't require manual updates
    // when new documentation pages are added to that folder.
    {
      type: 'category',
      label: 'Core Calculator Features',
      link: {
        type: 'generated-index',
        title: 'Core Calculator Features',
        description: 'Learn about the core scientific calculator functionalities, including basic arithmetic, trigonometric and logarithmic functions, memory operations, and user-defined variables.',
        slug: '/category/core-calculator-features',
      },
      items: [{ type: 'autogenerated', dirName: 'core-calculator' }],
    },
    // Category for Specialized Electronics Modes.
    // This follows the same autogeneration pattern for maintainability.
    {
      type: 'category',
      label: 'Electronics Modes',
      link: {
        type: 'generated-index',
        title: 'Electronics Modes',
        description: "Explore the specialized calculation modes designed for electronics professionals and hobbyists, including Ohm's Law, Resistor Combinations, Color Codes, and 555 Timer design.",
        slug: '/category/electronics-modes',
      },
      items: [{ type: 'autogenerated', dirName: 'electronics-modes' }],
    },
    // Category for the User-Extensible Custom Modes feature.
    // This follows the same autogeneration pattern.
    {
      type: 'category',
      label: 'Custom Calculation Modes',
      link: {
        type: 'generated-index',
        title: 'Custom Calculation Modes',
        description: 'Master the user-extensible framework. Learn how to create, manage, use, and share your own personalized calculation modes to streamline your unique workflows.',
        slug: '/category/custom-modes',
      },
      items: [{ type: 'autogenerated', dirName: 'custom-modes' }],
    },
  ],
};

module.exports = sidebars;