import { apiSlice } from '../api/apiSlice';
import {
  CalculationHistoryItem,
  UserVariable,
  CustomMode,
  CustomModeDto,
} from '../../shared/types/calculator';

/**
 * userApi is a set of endpoints that interact with the user-specific data
 * on the backend, such as calculation history, variables, and custom modes.
 * It extends the base apiSlice.
 */
export const userApi = apiSlice.injectEndpoints({
  endpoints: builder => ({
    //region User Data Aggregation
    getAllUserData: builder.query<
      {
        history: CalculationHistoryItem[];
        variables: UserVariable[];
        customModes: CustomMode[];
      },
      void
    >({
      query: () => 'user/all-data',
      providesTags: ['History', 'Variables', 'CustomModes'],
    }),
    //endregion

    //region History Endpoints
    getHistory: builder.query<CalculationHistoryItem[], void>({
      query: () => '/history',
      providesTags: result =>
        result
          ? [
              ...result.map(({ id }) => ({ type: 'History' as const, id })),
              { type: 'History', id: 'LIST' },
            ]
          : [{ type: 'History', id: 'LIST' }],
    }),
    addHistoryItem: builder.mutation<
      CalculationHistoryItem,
      Omit<CalculationHistoryItem, 'id' | 'createdAt'>
    >({
      query: newHistoryItem => ({
        url: '/history',
        method: 'POST',
        body: newHistoryItem,
      }),
      invalidatesTags: [{ type: 'History', id: 'LIST' }],
    }),
    //endregion

    //region Variables Endpoints
    getVariables: builder.query<UserVariable[], void>({
      query: () => '/variables',
      providesTags: result =>
        result
          ? [
              ...result.map(({ name }) => ({ type: 'Variables' as const, id: name })),
              { type: 'Variables', id: 'LIST' },
            ]
          : [{ type: 'Variables', id: 'LIST' }],
    }),
    saveVariable: builder.mutation<UserVariable, UserVariable>({
      query: variable => ({
        url: '/variables',
        method: 'POST', // Backend handles upsert logic
        body: variable,
      }),
      invalidatesTags: [{ type: 'Variables', id: 'LIST' }],
    }),
    deleteVariable: builder.mutation<void, string>({
      query: variableName => ({
        url: `/variables/${variableName}`,
        method: 'DELETE',
      }),
      invalidatesTags: [{ type: 'Variables', id: 'LIST' }],
    }),
    //endregion

    //region Custom Modes Endpoints
    getCustomModes: builder.query<CustomMode[], void>({
      query: () => '/custom-modes',
      providesTags: result =>
        result
          ? [
              ...result.map(({ id }) => ({ type: 'CustomModes' as const, id })),
              { type: 'CustomModes', id: 'LIST' },
            ]
          : [{ type: 'CustomModes', id: 'LIST' }],
    }),
    getCustomModeById: builder.query<CustomMode, string>({
      query: id => `/custom-modes/${id}`,
      providesTags: (_result, _error, id) => [{ type: 'CustomModes', id }],
    }),
    createCustomMode: builder.mutation<CustomMode, CustomModeDto>({
      query: newCustomMode => ({
        url: '/custom-modes',
        method: 'POST',
        body: newCustomMode,
      }),
      invalidatesTags: [{ type: 'CustomModes', id: 'LIST' }],
    }),
    updateCustomMode: builder.mutation<CustomMode, Partial<CustomMode> & Pick<CustomMode, 'id'>>({
      query: ({ id, ...patch }) => ({
        url: `/custom-modes/${id}`,
        method: 'PUT',
        body: patch,
      }),
      invalidatesTags: (_result, _error, { id }) => [
        { type: 'CustomModes', id },
        { type: 'CustomModes', id: 'LIST' },
      ],
    }),
    deleteCustomMode: builder.mutation<{ success: boolean; id: string }, string>({
      query(id) {
        return {
          url: `/custom-modes/${id}`,
          method: 'DELETE',
        };
      },
      invalidatesTags: (_result, _error, id) => [
        { type: 'CustomModes', id },
        { type: 'CustomModes', id: 'LIST' },
      ],
    }),
    importCustomMode: builder.mutation<CustomMode, { fileContent: string }>({
        query: ({ fileContent }) => ({
            url: '/custom-modes/import',
            method: 'POST',
            body: JSON.parse(fileContent),
        }),
        invalidatesTags: [{ type: 'CustomModes', id: 'LIST' }],
    }),
    //endregion

    //region User Account Endpoints
    deleteAccount: builder.mutation<void, { confirmation: string }>({
        query: (body) => ({
            url: '/user/me',
            method: 'DELETE',
            body,
        }),
        // Invalidate all caches on account deletion
        invalidatesTags: ['History', 'Variables', 'CustomModes'],
    }),
    //endregion
  }),
});

// Export hooks for usage in functional components, which are automatically
// generated by RTK Query.
export const {
  useGetAllUserDataQuery,
  useGetHistoryQuery,
  useAddHistoryItemMutation,
  useGetVariablesQuery,
  useSaveVariableMutation,
  useDeleteVariableMutation,
  useGetCustomModesQuery,
  useGetCustomModeByIdQuery,
  useCreateCustomModeMutation,
  useUpdateCustomModeMutation,
  useDeleteCustomModeMutation,
  useImportCustomModeMutation,
  useDeleteAccountMutation
} = userApi;